/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>



float calculadora_prog_1(char *host, float n1, float n2, char opr, CLIENT *clnt)
{
	float  *result_1;
	inputs  add_1_arg;
	float  *result_2;
	inputs  sub_1_arg;
	float  *result_3;
	inputs  mul_1_arg;
	float  *result_4;
	inputs  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if (opr == '+'){
		add_1_arg.num1 = n1;
		add_1_arg.num2 = n2;
		add_1_arg.operator = opr;
		
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_1;
	}
	else if (opr == '-'){
		add_1_arg.num1 = n1;
		add_1_arg.num2 = n2;
		add_1_arg.operator = opr;
		
		result_2 = sub_1(&sub_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		return *result_2;
		}
	}
	
	else if (opr == '*'){
		add_1_arg.num1 = n1;
		add_1_arg.num2 = n2;
		add_1_arg.operator = opr;
		
		result_3 = mul_1(&mul_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_3;
	}
	
	else if (opr == '/'){
		add_1_arg.num1 = n1;
		add_1_arg.num2 = n2;
		add_1_arg.operator = opr;
		
		if ( n2 == 0){
		printf("Error, división de cero no es válido");
		exit(0);
		}
		else{
			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			return *result_4;
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	float primer, segundo;
	char operador;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	printf("Calculadora RPC\n");
	printf("1. Suma(+)\n");
	printf("2. Resta(-)\n");
	printf("3. Multiplicación(*)\n");
	printf("4. División(/)\n");
	
	printf("Introduzca el primer numero: \n");
	scanf("%f", &primer);
	
	printf("Introduzca el segundo numero: \n");
	scanf("%f", &segundo);
	
	printf("Introduzca el símbolo de la operación que quiera realizar: \n");
	scanf("%s", &operador);
	
	host = argv[1];
	
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if (clnt == NULL){
	clnt_pcreateerror (host);
	exit(1);
	}
	
	printf("El resultado es = %f\n", calculadora_prog_1 (host, primer,segundo,operador, clnt));
exit (0);
}
